const products = [
  {
    '_id': '1',
    'name': 'لپ تاپ گیمینگ 15 اینچی ایسوس مدل ASUS TUF Dash 15 (2021)',
    'englishName': 'product (1)',
    'image': '/images/products',
    'gallery': {
      'src': [
        '/images/products/gallery/product (1)/product (1).jpg',
        '/images/products/gallery/product (1)/product (2).jpg',
        '/images/products/gallery/product (1)/product (3).jpg',
        '/images/products/gallery/product (1)/product (4).jpg',
        '/images/products/gallery/product (1)/product (5).jpg',
        '/images/products/gallery/product (1)/product (6).jpg',
        '/images/products/gallery/product (1)/product (7).jpg',
        '/images/products/gallery/product (1)/product (8).jpg',
        '/images/products/gallery/product (1)/product (9).jpg',
        '/images/products/gallery/product (1)/product (10).jpg',
        '/images/products/gallery/product (1)/product (11).jpg',
      ]
    },
    'description':
      'The all-new TUF Dash F15 puts powerful Windows 10 gaming in a super slim chassis. The latest 11th Gen Intel Core CPU and GeForce RTX GPU make gaming smooth on up to a blazing fast high refresh-rate display. Always ready for action, the Dash F15 darts with ease between gaming, streaming, and more.',
    'brand': 'ASUS',
    'category': 'Electronics',
    'price': '۶۰,۰۰۰',
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 91,
  },
  {
    '_id': '2',
    'name': 'هدفون بی سیم سامسونگ مدل Galaxy Buds Pro',
    'englishName': 'product (2)',
    'image': '/images/products',
    'gallery': {
      'src': [
        '/images/products/gallery/product (2)/product (1).jpg',
        '/images/products/gallery/product (2)/product (2).jpg',
        '/images/products/gallery/product (2)/product (3).jpg',
        '/images/products/gallery/product (2)/product (4).jpg',
        '/images/products/gallery/product (2)/product (5).jpg',
        '/images/products/gallery/product (2)/product (6).jpg',
        '/images/products/gallery/product (2)/product (7).jpg',
        '/images/products/gallery/product (2)/product (8).jpg',
        '/images/products/gallery/product (2)/product (9).jpg',
        '/images/products/gallery/product (2)/product (10).jpg',
        '/images/products/gallery/product (2)/product (11).jpg',
      ]
    },
    'description':
      'Introducing Xbox Series X, the fastest, most powerful Xbox ever. Play thousands of titles from four Generations of Consoles - all games look and play best on Xbox Series X. At the heart of Series X is the Xbox Velocity architecture, which pairs a custom SSD with integrated software for faster, streamlined gameplay with significantly reduced load times. Seamlessly move between multiple games in a Flash with quick resume. Explore rich new worlds and enjoy the action like never before with the unmatched 12 Teraflops of raw graphic processing power. Enjoy 4K gaming at up to 120 frames per second, advanced 3D spatial sound, and more. Get started with an instant library of 100+ high-quality games, including all new Xbox Game Studios titles the day they launch like Halo Infinite, with Xbox Game Pass ultimate (membership sold separately). If you purchased Xbox All Access at Amazon, please visit the Xbox website directly for steps on how to upgrade at a participating Xbox All Access retailer. Amazon is not an Xbox All Access participating retailer for Xbox Series X|S.',
    'brand': 'Micrisoft',
    'category': 'Electronics',
    'price': '۱۵۰,۰۰۰',
    'countInStock': 7,
    'rating': 4.9,
    'numReviews': 8245,
  },
  {
    '_id': '3',
    'name': 'هندزفری بلوتوثی لیتو مدل LB-014',
    'englishName': 'product (3)',
    'image': '/images/products',
    'gallery': {
      'src': [
        '/images/products/gallery/product (3)/product (1).jpg',
        '/images/products/gallery/product (3)/product (2).jpg',
        '/images/products/gallery/product (3)/product (3).jpg',
        '/images/products/gallery/product (3)/product (4).jpg',
        '/images/products/gallery/product (3)/product (5).jpg',
        '/images/products/gallery/product (3)/product (6).jpg',
        '/images/products/gallery/product (3)/product (7).jpg',
        '/images/products/gallery/product (3)/product (8).jpg',
        '/images/products/gallery/product (3)/product (9).jpg',
        '/images/products/gallery/product (3)/product (10).jpg',
        '/images/products/gallery/product (3)/product (11).jpg',
      ]
    },
    'description':
      'RUNMUS K2 gaming headset delivers 7.1 surround sound to enhance the immersive gaming experience. With the high responsive audio drivers, you can be better to make out the direction from which the sound is coming, like the gun fire, enemy footsteps and scenario indicators. Let you gain the competitive edge you need to take your game to the next level.',
    'brand': 'RUNMUS',
    'category': 'Electronics',
    'price': '۵,۰۰۰',
    'countInStock': 5,
    'rating': 4.4,
    'numReviews': 86699,
  },
  {
    '_id': '4',
    'name': 'هندزفری بی سیم ریمکس مدل RB-T35',
    'englishName': 'product (4)',
    'image': '/images/products',
    'gallery': {
      'src': [
        '/images/products/gallery/product (4)/product (1).jpg',
        '/images/products/gallery/product (4)/product (2).jpg',
        '/images/products/gallery/product (4)/product (3).jpg',
        '/images/products/gallery/product (4)/product (4).jpg',
        '/images/products/gallery/product (4)/product (5).jpg',
        '/images/products/gallery/product (4)/product (6).jpg',
        '/images/products/gallery/product (4)/product (7).jpg',
        '/images/products/gallery/product (4)/product (8).jpg',
        '/images/products/gallery/product (4)/product (9).jpg',
        '/images/products/gallery/product (4)/product (10).jpg',
        '/images/products/gallery/product (4)/product (11).jpg',
      ]
    },
    'description':
      'Logitech updated its iconic G502 gaming mouse to deliver even higher performance and more precise functionality than ever. Logitech G502 Hero high Performance Gaming mouse features the next generation Hero 16K Optical sensor, The highest performing and most efficient gaming sensor Logitech has ever made. An all-New lens and an updated tracking algorithm deliver ultra-precise tracking with no acceleration, smoothing, or filtering over the entire DPI range. Now, customize RGB mouse lighting to match your style and environment or sync to other Logitech G products. No matter your gaming style, It\'s easy to tweak G502 Hero to match your requirements, with custom profiles for your games, adjustable sensitivity from 200 up to 16, 000 DPI, and a tunable weight system that allows for tuning and balancing of up to five 3. 6G weights for just the right balance and feel.',
    'brand': 'Logitech G',
    'category': 'Electronics',
    'price': '۴۵,۰۰۰',
    'countInStock': 11,
    'rating': 4.7,
    'numReviews': 20411,
  },
  {
    '_id': '5',
    'name': 'هدفون بی سیم اپل مدل AirPods Pro 2021 همراه با محفظه شارژ',
    'englishName': 'product (5)',
    'image': '/images/products',
    'gallery': {
      'src': [
        '/images/products/gallery/product (5)/product (1).jpg',
        '/images/products/gallery/product (5)/product (2).jpg',
        '/images/products/gallery/product (5)/product (3).jpg',
        '/images/products/gallery/product (5)/product (4).jpg',
        '/images/products/gallery/product (5)/product (5).jpg',
        '/images/products/gallery/product (5)/product (6).jpg',
        '/images/products/gallery/product (5)/product (7).jpg',
        '/images/products/gallery/product (5)/product (8).jpg',
        '/images/products/gallery/product (5)/product (9).jpg',
        '/images/products/gallery/product (5)/product (10).jpg',
        '/images/products/gallery/product (5)/product (11).jpg',
      ]
    },
    'description':
      'Oculus Quest 2 is our most advanced all-in-one VR system yet. Every detail has been engineered to make virtual worlds adapt to your movements, letting you explore awe-inspiring games and experiences with unparalleled freedom. No PC or console required. Get the most out of each moment with blazing-fast performance and next-generation graphics. Stay focused with a stunning display that features 50% more pixels than the original Quest. Or take a break from the action and grab front-row seats to live concerts, exclusive events and more. The redesigned Touch controllers feature improved ergonomics and intuitive controls that transport your gestures, motions and actions directly into VR. You can even connect your VR headset to a gaming-compatible computer with an Oculus Link cable to access hundreds of PC VR games and experiences. Quest 2 also lets you bring your friends into the action. With live casting, you can share your VR experience with people around you. Or meet up with friends in virtual worlds to battle in multiplayer competitions or just spend some time together. With Oculus Quest 2, there’s no end in sight to what you can play, create and discover in virtual reality.',
    'brand': 'Oculus',
    'category': 'Electronics',
    'price': '۵۰۰,۰۰۰',
    'countInStock': 7,
    'rating': 2.8,
    'numReviews': 51196,
  },
  {
    '_id': '6',
    'name': 'هندزفری لیتو مدل LE-6',
    'englishName': 'product (6)',
    'image': '/images/products',
    'gallery': {
      'src': [
        '/images/products/gallery/product (6)/product (1).jpg',
        '/images/products/gallery/product (6)/product (2).jpg',
        '/images/products/gallery/product (6)/product (3).jpg',
        '/images/products/gallery/product (6)/product (4).jpg',
        '/images/products/gallery/product (6)/product (5).jpg',
        '/images/products/gallery/product (6)/product (6).jpg',
        '/images/products/gallery/product (6)/product (7).jpg',
        '/images/products/gallery/product (6)/product (8).jpg',
        '/images/products/gallery/product (6)/product (9).jpg',
        '/images/products/gallery/product (6)/product (10).jpg',
        '/images/products/gallery/product (6)/product (11).jpg',
      ]
    },
    'description':
      'GameSir T4 pro\'s chip has been upgraded in all aspects. This chip can now meet the hopes of players using GameSir T4 pro on multiple platforms. It only takes a few simple steps to use this controller on Apple, Android, Android TV Box, Mac OS, PC, and Switch.',
    'brand': 'GameSir',
    'category': 'Electronics',
    'price': '۵۰۰,۰۰۰',
    'countInStock': 0,
    'rating': 4.3,
    'numReviews': 4040,
  },
  {
    '_id': '7',
    'name': 'هندزفری لیتو مدل LE-7',
    'englishName': 'product (7)',
    'image': '/images/products',
    'gallery': {
      'src': [
        '/images/products/gallery/product (7)/product (1).jpg',
        '/images/products/gallery/product (7)/product (2).jpg',
        '/images/products/gallery/product (7)/product (3).jpg',
        '/images/products/gallery/product (7)/product (4).jpg',
        '/images/products/gallery/product (7)/product (5).jpg',
        '/images/products/gallery/product (7)/product (6).jpg',
        '/images/products/gallery/product (7)/product (7).jpg',
        '/images/products/gallery/product (7)/product (8).jpg',
        '/images/products/gallery/product (7)/product (9).jpg',
        '/images/products/gallery/product (7)/product (10).jpg',
        '/images/products/gallery/product (7)/product (11).jpg',
      ]
    },
    'description':
      'GameSir T4 pro\'s chip has been upgraded in all aspects. This chip can now meet the hopes of players using GameSir T4 pro on multiple platforms. It only takes a few simple steps to use this controller on Apple, Android, Android TV Box, Mac OS, PC, and Switch.',
    'brand': 'GameSir',
    'category': 'Electronics',
    'price': '۵۰۰,۰۰۰',
    'countInStock': 0,
    'rating': 4.3,
    'numReviews': 4040,
  },
  {
    '_id': '8',
    'name': '8 هندزفری لیتو مدل LE-',
    'englishName': 'product (8)',
    'image': '/images/products',
    'gallery': {
      'src': [
        '/images/products/gallery/product (8)/product (1).jpg',
        '/images/products/gallery/product (8)/product (2).jpg',
        '/images/products/gallery/product (8)/product (3).jpg',
        '/images/products/gallery/product (8)/product (4).jpg',
        '/images/products/gallery/product (8)/product (5).jpg',
        '/images/products/gallery/product (8)/product (6).jpg',
        '/images/products/gallery/product (8)/product (7).jpg',
        '/images/products/gallery/product (8)/product (8).jpg',
        '/images/products/gallery/product (8)/product (9).jpg',
        '/images/products/gallery/product (8)/product (10).jpg',
        '/images/products/gallery/product (8)/product (11).jpg',
      ]
    },
    'description':
      'GameSir T4 pro\'s chip has been upgraded in all aspects. This chip can now meet the hopes of players using GameSir T4 pro on multiple platforms. It only takes a few simple steps to use this controller on Apple, Android, Android TV Box, Mac OS, PC, and Switch.',
    'brand': 'GameSir',
    'category': 'Electronics',
    'price': '۵۰۰,۰۰۰',
    'countInStock': 0,
    'rating': 1.3,
    'numReviews': 4040,
  },
  {
    '_id': '9',
    'name': '9',
    'englishName': 'product (7)',
    'image': '/images/products',
    'gallery': {
      'src': [
        '/images/products/gallery/product (9)/product (1).jpg',
        '/images/products/gallery/product (9)/product (2).jpg',
        '/images/products/gallery/product (9)/product (3).jpg',
        '/images/products/gallery/product (9)/product (4).jpg',
        '/images/products/gallery/product (9)/product (5).jpg',
        '/images/products/gallery/product (9)/product (6).jpg',
        '/images/products/gallery/product (9)/product (7).jpg',
        '/images/products/gallery/product (9)/product (8).jpg',
        '/images/products/gallery/product (9)/product (9).jpg',
        '/images/products/gallery/product (9)/product (10).jpg',
        '/images/products/gallery/product (9)/product (11).jpg',
      ]
    },
    'description':
      'GameSir T4 pro\'s chip has been upgraded in all aspects. This chip can now meet the hopes of players using GameSir T4 pro on multiple platforms. It only takes a few simple steps to use this controller on Apple, Android, Android TV Box, Mac OS, PC, and Switch.',
    'brand': 'GameSir',
    'category': 'Electronics',
    'price': '۵۰۰,۰۰۰',
    'countInStock': 0,
    'rating': 4.3,
    'numReviews': 4040,
  },
  {
    '_id': '10',
    'name': '10',
    'englishName': 'product (8)',
    'image': '/images/products',
    'gallery': {
      'src': [
        '/images/products/gallery/product (10)/product (1).jpg',
        '/images/products/gallery/product (10)/product (2).jpg',
        '/images/products/gallery/product (10)/product (3).jpg',
        '/images/products/gallery/product (10)/product (4).jpg',
        '/images/products/gallery/product (10)/product (5).jpg',
        '/images/products/gallery/product (10)/product (6).jpg',
        '/images/products/gallery/product (10)/product (7).jpg',
        '/images/products/gallery/product (10)/product (8).jpg',
        '/images/products/gallery/product (10)/product (9).jpg',
        '/images/products/gallery/product (10)/product (10).jpg',
        '/images/products/gallery/product (10)/product (11).jpg',
      ]
    },
    'description':
      'GameSir T4 pro\'s chip has been upgraded in all aspects. This chip can now meet the hopes of players using GameSir T4 pro on multiple platforms. It only takes a few simple steps to use this controller on Apple, Android, Android TV Box, Mac OS, PC, and Switch.',
    'brand': 'GameSir',
    'category': 'Electronics',
    'price': '۵۰۰,۰۰۰',
    'countInStock': 0,
    'rating': 1.3,
    'numReviews': 4040,
  },
  {
    '_id': '11',
    'name': 'هارددیسک اینترنال وسترن دیجیتال مدل Purple WD80PURZ ظرفیت 8 ترابایت',
    'englishName': 'Western Digital Purple WD80PURZ Internal Hard Disk 8TB',
    'image': '/images/products',
    'gallery': {
      'src': [
        '/images/products/gallery/product (11)/product (1).jpg',
        '/images/products/gallery/product (11)/product (2).jpg',
        '/images/products/gallery/product (11)/product (3).jpg',
        '/images/products/gallery/product (11)/product (4).jpg',
        '/images/products/gallery/product (11)/product (5).jpg',
        '/images/products/gallery/product (11)/product (6).jpg',
        '/images/products/gallery/product (11)/product (7).jpg',
        '/images/products/gallery/product (11)/product (8).jpg',
        '/images/products/gallery/product (11)/product (9).jpg',
        '/images/products/gallery/product (11)/product (10).jpg',
        '/images/products/gallery/product (11)/product (11).jpg',
      ]
    },
    'description':
      'GameSir T4 pro\'s chip has been upgraded in all aspects. This chip can now meet the hopes of players using GameSir T4 pro on multiple platforms. It only takes a few simple steps to use this controller on Apple, Android, Android TV Box, Mac OS, PC, and Switch.',
    'brand': 'GameSir',
    'category': 'Electronics',
    'price': '۵۰۰,۰۰۰',
    'countInStock': 0,
    'rating': 4.3,
    'numReviews': 4040,
  },
  {
    '_id': '12',
    'name': '12',
    'englishName': 'product (8)',
    'image': '/images/products',
    'gallery': {
      'src': [
        '/images/products/gallery/product (12)/product (1).jpg',
        '/images/products/gallery/product (12)/product (2).jpg',
        '/images/products/gallery/product (12)/product (3).jpg',
        '/images/products/gallery/product (12)/product (4).jpg',
        '/images/products/gallery/product (12)/product (5).jpg',
        '/images/products/gallery/product (12)/product (6).jpg',
        '/images/products/gallery/product (12)/product (7).jpg',
        '/images/products/gallery/product (12)/product (8).jpg',
        '/images/products/gallery/product (12)/product (9).jpg',
        '/images/products/gallery/product (12)/product (10).jpg',
        '/images/products/gallery/product (12)/product (11).jpg',
      ]
    },
    'description':
      'GameSir T4 pro\'s chip has been upgraded in all aspects. This chip can now meet the hopes of players using GameSir T4 pro on multiple platforms. It only takes a few simple steps to use this controller on Apple, Android, Android TV Box, Mac OS, PC, and Switch.',
    'brand': 'GameSir',
    'category': 'Electronics',
    'price': '۵۰۰,۰۰۰',
    'countInStock': 0,
    'rating': 1.3,
    'numReviews': 4040,
  },
  {
    '_id': '13',
    'name': '13',
    'englishName': 'product (7)',
    'image': '/images/products',
    'gallery': {
      'src': [
        '/images/products/gallery/product (13)/product (1).jpg',
        '/images/products/gallery/product (13)/product (2).jpg',
        '/images/products/gallery/product (13)/product (3).jpg',
        '/images/products/gallery/product (13)/product (4).jpg',
        '/images/products/gallery/product (13)/product (5).jpg',
        '/images/products/gallery/product (13)/product (6).jpg',
        '/images/products/gallery/product (13)/product (7).jpg',
        '/images/products/gallery/product (13)/product (8).jpg',
        '/images/products/gallery/product (13)/product (9).jpg',
        '/images/products/gallery/product (13)/product (10).jpg',
        '/images/products/gallery/product (13)/product (11).jpg',
      ]
    },
    'description':
      'GameSir T4 pro\'s chip has been upgraded in all aspects. This chip can now meet the hopes of players using GameSir T4 pro on multiple platforms. It only takes a few simple steps to use this controller on Apple, Android, Android TV Box, Mac OS, PC, and Switch.',
    'brand': 'GameSir',
    'category': 'Electronics',
    'price': '۵۰۰,۰۰۰',
    'countInStock': 0,
    'rating': 4.3,
    'numReviews': 4040,
  },
  {
    '_id': '14',
    'name': '14',
    'englishName': 'product (8)',
    'image': '/images/products',
    'gallery': {
      'src': [
        '/images/products/gallery/product (14)/product (1).jpg',
        '/images/products/gallery/product (14)/product (2).jpg',
        '/images/products/gallery/product (14)/product (3).jpg',
        '/images/products/gallery/product (14)/product (4).jpg',
        '/images/products/gallery/product (14)/product (5).jpg',
        '/images/products/gallery/product (14)/product (6).jpg',
        '/images/products/gallery/product (14)/product (7).jpg',
        '/images/products/gallery/product (14)/product (8).jpg',
        '/images/products/gallery/product (14)/product (9).jpg',
        '/images/products/gallery/product (14)/product (10).jpg',
        '/images/products/gallery/product (14)/product (11).jpg',
      ]
    },
    'description':
      'GameSir T4 pro\'s chip has been upgraded in all aspects. This chip can now meet the hopes of players using GameSir T4 pro on multiple platforms. It only takes a few simple steps to use this controller on Apple, Android, Android TV Box, Mac OS, PC, and Switch.',
    'brand': 'GameSir',
    'category': 'Electronics',
    'price': '۵۰۰,۰۰۰',
    'countInStock': 0,
    'rating': 1.3,
    'numReviews': 4040,
  },
  {
    '_id': '15',
    'name': '15',
    'englishName': 'product (7)',
    'image': '/images/products',
    'gallery': {
      'src': [
        '/images/products/gallery/product (15)/product (1).jpg',
        '/images/products/gallery/product (15)/product (2).jpg',
        '/images/products/gallery/product (15)/product (3).jpg',
        '/images/products/gallery/product (15)/product (4).jpg',
        '/images/products/gallery/product (15)/product (5).jpg',
        '/images/products/gallery/product (15)/product (6).jpg',
        '/images/products/gallery/product (15)/product (7).jpg',
        '/images/products/gallery/product (15)/product (8).jpg',
        '/images/products/gallery/product (15)/product (9).jpg',
        '/images/products/gallery/product (15)/product (10).jpg',
        '/images/products/gallery/product (15)/product (11).jpg',
      ]
    },
    'description':
      'GameSir T4 pro\'s chip has been upgraded in all aspects. This chip can now meet the hopes of players using GameSir T4 pro on multiple platforms. It only takes a few simple steps to use this controller on Apple, Android, Android TV Box, Mac OS, PC, and Switch.',
    'brand': 'GameSir',
    'category': 'Electronics',
    'price': '۵۰۰,۰۰۰',
    'countInStock': 0,
    'rating': 4.3,
    'numReviews': 4040,
  },
  {
    '_id': '16',
    'name': '16',
    'englishName': 'product (8)',
    'image': '/images/products',
    'gallery': {
      'src': [
        '/images/products/gallery/product (16)/product (1).jpg',
        '/images/products/gallery/product (16)/product (2).jpg',
        '/images/products/gallery/product (16)/product (3).jpg',
        '/images/products/gallery/product (16)/product (4).jpg',
        '/images/products/gallery/product (16)/product (5).jpg',
        '/images/products/gallery/product (16)/product (6).jpg',
        '/images/products/gallery/product (16)/product (7).jpg',
        '/images/products/gallery/product (16)/product (8).jpg',
        '/images/products/gallery/product (16)/product (9).jpg',
        '/images/products/gallery/product (16)/product (10).jpg',
        '/images/products/gallery/product (16)/product (11).jpg',
      ]
    },
    'description':
      'GameSir T4 pro\'s chip has been upgraded in all aspects. This chip can now meet the hopes of players using GameSir T4 pro on multiple platforms. It only takes a few simple steps to use this controller on Apple, Android, Android TV Box, Mac OS, PC, and Switch.',
    'brand': 'GameSir',
    'category': 'Electronics',
    'price': '۵۰۰,۰۰۰',
    'countInStock': 0,
    'rating': 1.3,
    'numReviews': 4040,
  },
  {
    '_id': '17',
    'name': '17',
    'englishName': 'product (7)',
    'image': '/images/products',
    'gallery': {
      'src': [
        '/images/products/gallery/product (17)/product (1).jpg',
        '/images/products/gallery/product (17)/product (2).jpg',
        '/images/products/gallery/product (17)/product (3).jpg',
        '/images/products/gallery/product (17)/product (4).jpg',
        '/images/products/gallery/product (17)/product (5).jpg',
        '/images/products/gallery/product (17)/product (6).jpg',
        '/images/products/gallery/product (17)/product (7).jpg',
        '/images/products/gallery/product (17)/product (8).jpg',
        '/images/products/gallery/product (17)/product (9).jpg',
        '/images/products/gallery/product (17)/product (10).jpg',
        '/images/products/gallery/product (17)/product (11).jpg',
      ]
    },
    'description':
      'GameSir T4 pro\'s chip has been upgraded in all aspects. This chip can now meet the hopes of players using GameSir T4 pro on multiple platforms. It only takes a few simple steps to use this controller on Apple, Android, Android TV Box, Mac OS, PC, and Switch.',
    'brand': 'GameSir',
    'category': 'Electronics',
    'price': '۵۰۰,۰۰۰',
    'countInStock': 0,
    'rating': 4.3,
    'numReviews': 4040,
  },
  {
    '_id': '18',
    'name': '18',
    'englishName': 'product (8)',
    'image': '/images/products',
    'gallery': {
      'src': [
        '/images/products/gallery/product (18)/product (1).jpg',
        '/images/products/gallery/product (18)/product (2).jpg',
        '/images/products/gallery/product (18)/product (3).jpg',
        '/images/products/gallery/product (18)/product (4).jpg',
        '/images/products/gallery/product (18)/product (5).jpg',
        '/images/products/gallery/product (18)/product (6).jpg',
        '/images/products/gallery/product (18)/product (7).jpg',
        '/images/products/gallery/product (18)/product (8).jpg',
        '/images/products/gallery/product (18)/product (9).jpg',
        '/images/products/gallery/product (18)/product (10).jpg',
        '/images/products/gallery/product (18)/product (11).jpg',
      ]
    },
    'description':
      'GameSir T4 pro\'s chip has been upgraded in all aspects. This chip can now meet the hopes of players using GameSir T4 pro on multiple platforms. It only takes a few simple steps to use this controller on Apple, Android, Android TV Box, Mac OS, PC, and Switch.',
    'brand': 'GameSir',
    'category': 'Electronics',
    'price': '۵۰۰,۰۰۰',
    'countInStock': 0,
    'rating': 1.3,
    'numReviews': 4040,
  },
  {
    '_id': '19',
    'name': '19',
    'englishName': 'product (7)',
    'image': '/images/products',
    'gallery': {
      'src': [
        '/images/products/gallery/product (19)/product (1).jpg',
        '/images/products/gallery/product (19)/product (2).jpg',
        '/images/products/gallery/product (19)/product (3).jpg',
        '/images/products/gallery/product (19)/product (4).jpg',
        '/images/products/gallery/product (19)/product (5).jpg',
        '/images/products/gallery/product (19)/product (6).jpg',
        '/images/products/gallery/product (19)/product (7).jpg',
        '/images/products/gallery/product (19)/product (8).jpg',
        '/images/products/gallery/product (19)/product (9).jpg',
        '/images/products/gallery/product (19)/product (10).jpg',
        '/images/products/gallery/product (19)/product (11).jpg',
      ]
    },
    'description':
      'GameSir T4 pro\'s chip has been upgraded in all aspects. This chip can now meet the hopes of players using GameSir T4 pro on multiple platforms. It only takes a few simple steps to use this controller on Apple, Android, Android TV Box, Mac OS, PC, and Switch.',
    'brand': 'GameSir',
    'category': 'Electronics',
    'price': '۵۰۰,۰۰۰',
    'countInStock': 0,
    'rating': 4.3,
    'numReviews': 4040,
  },
  {
    '_id': '20',
    'name': '8 هندزفری لیتو مدل LE-',
    'englishName': 'product (8)',
    'image': '/images/products',
    'gallery': {
      'src': [
        '/images/products/gallery/product (20)/product (1).jpg',
        '/images/products/gallery/product (20)/product (2).jpg',
        '/images/products/gallery/product (20)/product (3).jpg',
        '/images/products/gallery/product (20)/product (4).jpg',
        '/images/products/gallery/product (20)/product (5).jpg',
        '/images/products/gallery/product (20)/product (6).jpg',
        '/images/products/gallery/product (20)/product (7).jpg',
        '/images/products/gallery/product (20)/product (8).jpg',
        '/images/products/gallery/product (20)/product (9).jpg',
        '/images/products/gallery/product (20)/product (10).jpg',
        '/images/products/gallery/product (20)/product (11).jpg',
      ]
    },
    'description':
      'GameSir T4 pro\'s chip has been upgraded in all aspects. This chip can now meet the hopes of players using GameSir T4 pro on multiple platforms. It only takes a few simple steps to use this controller on Apple, Android, Android TV Box, Mac OS, PC, and Switch.',
    'brand': 'GameSir',
    'category': 'Electronics',
    'price': '۵۰۰,۰۰۰',
    'countInStock': 0,
    'rating': 1.3,
    'numReviews': 4040,
  },
  {
    '_id': '21',
    'name': '21',
    'englishName': 'product (7)',
    'image': '/images/products',
    'gallery': {
      'src': [
        '/images/products/gallery/product (21)/product (1).jpg',
        '/images/products/gallery/product (21)/product (2).jpg',
        '/images/products/gallery/product (21)/product (3).jpg',
        '/images/products/gallery/product (21)/product (4).jpg',
        '/images/products/gallery/product (21)/product (5).jpg',
        '/images/products/gallery/product (21)/product (6).jpg',
        '/images/products/gallery/product (21)/product (7).jpg',
        '/images/products/gallery/product (21)/product (8).jpg',
        '/images/products/gallery/product (21)/product (9).jpg',
        '/images/products/gallery/product (21)/product (10).jpg',
        '/images/products/gallery/product (21)/product (11).jpg',
      ]
    },
    'description':
      'GameSir T4 pro\'s chip has been upgraded in all aspects. This chip can now meet the hopes of players using GameSir T4 pro on multiple platforms. It only takes a few simple steps to use this controller on Apple, Android, Android TV Box, Mac OS, PC, and Switch.',
    'brand': 'GameSir',
    'category': 'Electronics',
    'price': '۵۰۰,۰۰۰',
    'countInStock': 0,
    'rating': 4.3,
    'numReviews': 4040,
  },
  {
    '_id': '22',
    'name': '22',
    'englishName': 'product (8)',
    'image': '/images/products',
    'gallery': {
      'src': [
        '/images/products/gallery/product (22)/product (1).jpg',
        '/images/products/gallery/product (22)/product (2).jpg',
        '/images/products/gallery/product (22)/product (3).jpg',
        '/images/products/gallery/product (22)/product (4).jpg',
        '/images/products/gallery/product (22)/product (5).jpg',
        '/images/products/gallery/product (22)/product (6).jpg',
        '/images/products/gallery/product (22)/product (7).jpg',
        '/images/products/gallery/product (22)/product (8).jpg',
        '/images/products/gallery/product (22)/product (9).jpg',
        '/images/products/gallery/product (22)/product (10).jpg',
        '/images/products/gallery/product (22)/product (11).jpg',
      ]
    },
    'description':
      'GameSir T4 pro\'s chip has been upgraded in all aspects. This chip can now meet the hopes of players using GameSir T4 pro on multiple platforms. It only takes a few simple steps to use this controller on Apple, Android, Android TV Box, Mac OS, PC, and Switch.',
    'brand': 'GameSir',
    'category': 'Electronics',
    'price': '۵۰۰,۰۰۰',
    'countInStock': 0,
    'rating': 1.3,
    'numReviews': 4040,
  },
  {
    '_id': '23',
    'name': '23',
    'englishName': 'product (7)',
    'image': '/images/products',
    'gallery': {
      'src': [
        '/images/products/gallery/product (23)/product (1).jpg',
        '/images/products/gallery/product (23)/product (2).jpg',
        '/images/products/gallery/product (23)/product (3).jpg',
        '/images/products/gallery/product (23)/product (4).jpg',
        '/images/products/gallery/product (23)/product (5).jpg',
        '/images/products/gallery/product (23)/product (6).jpg',
        '/images/products/gallery/product (23)/product (7).jpg',
        '/images/products/gallery/product (23)/product (8).jpg',
        '/images/products/gallery/product (23)/product (9).jpg',
        '/images/products/gallery/product (23)/product (10).jpg',
        '/images/products/gallery/product (23)/product (11).jpg',
      ]
    },
    'description':
      'GameSir T4 pro\'s chip has been upgraded in all aspects. This chip can now meet the hopes of players using GameSir T4 pro on multiple platforms. It only takes a few simple steps to use this controller on Apple, Android, Android TV Box, Mac OS, PC, and Switch.',
    'brand': 'GameSir',
    'category': 'Electronics',
    'price': '۵۰۰,۰۰۰',
    'countInStock': 0,
    'rating': 4.3,
    'numReviews': 4040,
  },
  {
    '_id': 24,
    'name': '24',
    'englishName': 'product (8)',
    'image': '/images/products',
    'gallery': {
      'src': [
        '/images/products/gallery/product (24)/product (1).jpg',
        '/images/products/gallery/product (24)/product (2).jpg',
        '/images/products/gallery/product (24)/product (3).jpg',
        '/images/products/gallery/product (24)/product (4).jpg',
        '/images/products/gallery/product (24)/product (5).jpg',
        '/images/products/gallery/product (24)/product (6).jpg',
        '/images/products/gallery/product (24)/product (7).jpg',
        '/images/products/gallery/product (24)/product (8).jpg',
        '/images/products/gallery/product (24)/product (9).jpg',
        '/images/products/gallery/product (24)/product (10).jpg',
        '/images/products/gallery/product (24)/product (11).jpg',
      ]
    },
    'description':
      'GameSir T4 pro\'s chip has been upgraded in all aspects. This chip can now meet the hopes of players using GameSir T4 pro on multiple platforms. It only takes a few simple steps to use this controller on Apple, Android, Android TV Box, Mac OS, PC, and Switch.',
    'brand': 'GameSir',
    'category': 'Electronics',
    'price': '۵۰۰,۰۰۰',
    'countInStock': 0,
    'rating': 1.3,
    'numReviews': 4040,
  }
]

export const getProduct = (id) => {
  return products.find(product => product._id === id)
}

export default products
