export const PRODUCT_LIST_BY_USER_REQUEST = 'PRODUCT_LIST_BY_USER_REQUEST'
export const PRODUCT_LIST_BY_USER_SUCCESS = 'PRODUCT_LIST_BY_USER_SUCCESS'
export const PRODUCT_LIST_BY_USER_FAIL = 'PRODUCT_LIST_BY_USER_FAIL'

export const ADD_FAVORITE_PRODUCT_REQUEST = 'ADD_FAVORITE_PRODUCT_REQUEST'
export const ADD_FAVORITE_PRODUCT_SUCCESS = 'ADD_FAVORITE_PRODUCT_SUCCESS'
export const ADD_FAVORITE_PRODUCT_FAIL = 'ADD_FAVORITE_PRODUCT_FAIL'

export const ADD_TO_COMPARE_PRODUCT_REQUEST = 'ADD_TO_COMPARE_PRODUCT_REQUEST'
export const ADD_TO_COMPARE_PRODUCT_SUCCESS = 'ADD_TO_COMPARE_PRODUCT_SUCCESS'
export const ADD_TO_COMPARE_PRODUCT_FAIL = 'ADD_TO_COMPARE_PRODUCT_FAIL'
