# Generated by Django 4.1 on 2023-04-14 15:00

import autoslug.fields
import base.models
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='شماره موبایل')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persianName', models.CharField(max_length=100, verbose_name='نام فارسی')),
                ('englishName', models.CharField(max_length=100, verbose_name='نام انگلیسی')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='englishName', unique=True)),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('english_name', models.CharField(max_length=100, null=True)),
                ('isManeCat', models.BooleanField(default=False, verbose_name='نمایش در دسته بندی اصلی')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='english_name', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('getRoute', models.CharField(blank=True, max_length=300, null=True, verbose_name='مسیر دسته بندی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='base.category')),
            ],
            options={
                'verbose_name_plural': 'دسته بندی ها',
                'unique_together': {('slug', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persianName', models.CharField(max_length=100, verbose_name='نام فارسی')),
                ('englishName', models.CharField(max_length=100, verbose_name='نام انگلیسی')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='englishName', unique=True)),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryProduct',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام محصول')),
                ('image', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to=base.models.upload_gallery_images_path, verbose_name='تصویر')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('paymentMethod', models.CharField(blank=True, max_length=200, null=True, verbose_name='روش پرداخت')),
                ('shippingPrice', models.IntegerField(blank=True, null=True, verbose_name='هزینه حمل و نقل')),
                ('totalPrice', models.IntegerField(blank=True, null=True, verbose_name='قبمت کل')),
                ('isPaid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('paidAt', models.DateTimeField(blank=True, null=True, verbose_name='پرداخت شده در')),
                ('isDelivered', models.BooleanField(default=False, verbose_name='تحویل شده')),
                ('deliveredAt', models.DateTimeField(blank=True, null=True, verbose_name='تحویل شده در')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('isCanceled', models.BooleanField(default=False, verbose_name='کنسل شده')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کابر')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام محصول')),
                ('english_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام انگلیسی محصول')),
                ('image', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to=base.models.upload_image_path, verbose_name='تصویر')),
                ('shortDescription', models.TextField(blank=True, null=True, verbose_name='توضیجات کوتاه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیجات')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='امتیاز')),
                ('numReviews', models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد دیدگاه')),
                ('discountless_price', models.IntegerField(blank=True, null=True, verbose_name='قیمت خط خورده')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='قیمت')),
                ('discountPrice', models.IntegerField(blank=True, null=True, verbose_name='درصد تخفیف')),
                ('countInStock', models.IntegerField(blank=True, default=0, null=True, verbose_name='موجودی انبار')),
                ('maxSale', models.IntegerField(blank=True, default=0, null=True, verbose_name='سقف فروش در هر سفارش (صفر برای نداشتن سقف)')),
                ('totalSale', models.IntegerField(blank=True, default=0, null=True, verbose_name='جمع تعداد فروش')),
                ('visitCount', models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد بازدید')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.brand', verbose_name='برند')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.category', verbose_name='دسته بندی')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.color', verbose_name='رنگ')),
                ('gallery_images', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.galleryproduct', verbose_name='تصاویر گالری')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('subtitle', models.TextField(verbose_name='توضیحات')),
                ('url', models.CharField(max_length=100, verbose_name='آدرس')),
                ('image', models.ImageField(blank=True, null=True, upload_to=base.models.upload_image_path, verbose_name='تصویر ۴۵۰ در ۱۵۰۰')),
                ('active', models.BooleanField(default=False, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدرها',
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='آدرس')),
                ('city', models.CharField(blank=True, max_length=200, null=True, verbose_name='شهر')),
                ('postalCode', models.CharField(blank=True, max_length=200, null=True, verbose_name='کدپستی')),
                ('shippingPrice', models.IntegerField(blank=True, null=True, verbose_name='هزینه حمل و نقل')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.order', verbose_name='سفارش')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام')),
                ('rating', models.IntegerField(blank=True, default=0, null=True, verbose_name='امتیاز')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='دیدگاه')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.product', verbose_name='محصول')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کابر')),
            ],
        ),
        migrations.CreateModel(
            name='ProductListByUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listName', models.CharField(choices=[('fav', 'علاقه\u200cمندی\u200cها'), ('com', 'مقایسه')], max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.product', verbose_name='محصول')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کابر')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام')),
                ('qty', models.IntegerField(blank=True, default=0, null=True, verbose_name='qty')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='قیمت')),
                ('image', models.CharField(blank=True, max_length=200, null=True, verbose_name='تصویر')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.product', verbose_name='محصول')),
            ],
        ),
    ]
